lag_house_dbt:
  outputs:
    dev:
      dataset: listings_transform
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/victoressien/Desktop/lag-house/keys/vee-de-portfolio.json
      location: US
      method: service-account
      priority: interactive
      project: vee-de
      threads: 1
      type: bigquery
  target: dev