name: CI/CD Pipeline

on:
  push:
    branches: [ master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Add dags to PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/dags" >> $GITHUB_ENV

    # - name: Run tests
    #   run: python -m pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Deploy to Cloud Composer
      run: |
        gcloud composer environments update lag-house-composer-1 \
          --location us-central1 \
          --update-pypi-packages-from-file requirements.txt
        gcloud composer environments storage dags import \
          --environment lag-house-composer-1 \
          --location us-central1 \
          --source dags/
